### PR TITLE
Add asayer.io/openreplay.com

### PR DESCRIPTION
**Pull request by Lelenaic**
Hi,
I would like to add Asayer/OpenReplay which is a cloud platform providing a JS integration to record the user's browser interactions (similar to hotjar or things like this).

Here's their website: https://www.openreplay.com

Thanks!

### CODE REVIEW

**Comment by jawz101** [comment]
This list isn't for website blocking

**Comment by Lelenaic** [comment]
Well this is not website blocking, juste their script recording your browser. Isn't it the purpose of this list?

**Comment by jawz101** [comment]
Mobile ad & tracking networks.  Not webpage content.  The "free coins if you watch this video" or "we track your phone's location to serve you ads" type stuff.

I would think EasyPrivacy or Adguard Tracking Protection might be more appropriate lists for web tracking.

**Comment by spirillen** [comment]
Hey @Lelenaic is there any change you can remember how you found those sub-domains??

**Comment by Lelenaic** [comment]
Hi,
If you register on openreplay, their JS integration script gives this subdomain. asayer.io is just their old name.

**Comment by spirillen** [comment]
Thanks

**Pull request closed without merging**
