### PR TITLE
Heuristics-Based Additions of Some Entries

### PR DESCRIPTION
**Pull request by sr093906**

### CODE REVIEW

**Comment by spirillen** [comment]
> _No description provided._

1. Why are these listed
2. Are all these seen on any mobile device??
    - I know @jawz101 will ask you this as the first question :smile:

**Comment by sr093906** [comment]
1. The domain names suggest a lot. That's what the heuristics means.
2. No.  Otherwise, I will not say the additions are heuristics-based.

**Comment by sr093906** [comment]
A small part of the words used to list the domains are 

ad/ads/adv
ana(lytic)
api
app
ark*
awake/awa
banner
beacon
bug
click/clk
crash
data
delivery
dmp
dsp
event
geo
grow
imp(ression)
insight
lbs
loc
log
match
measure
metric
mon
perf
ping
pos(ition)
pv
report/rpt
sdk
sentry
ssp
stat
status
tag
tele
tongji/tj
tr(ack)

**Comment by spirillen** [comment]
LOL, just tested the list with PyFunceble myself :smiling_imp: and actually made a new feature request based on this PR :)

**Comment by sr093906** [comment]
Thanks.

**Comment by jawz101** [comment]
I can't use this sort of approach.  It causes too many false positives and I also like to keep the list pretty lean to just observed domains.  Back when I had the MobileAdTrackers list I had done this sort of approach by starting with the [Cisco/Umbrella/OpenDNS Popularity List](http://s3-us-west-1.amazonaws.com/umbrella-static/index.html) and paired it down from the 1 million entries to about 20,000.  I was quickly scrambling to remove reported breakage and quickly scrapped the whole change because it wasn't reliable.

I suggest using a DNS resolver you can observe such as Pi-Hole or NextDNS and see what traffic comes across it, block some, and see what happens.  Bottom line is I think a host file should be for observed DNS lookup activity and not heuristics.  That could be for something more like a browser ad blocker or another blocking mechanism that supports advanced syntax.  Just my thoughts.

**Comment by jawz101** [comment]
I'd also consider segment(ation), rtb (aka real-time bidding), tric, pixel (for pixel-based web monitoring), counter.  I can't think of any others off the top of my head.

Something like status can block a lot of status pages.

**Comment by sr093906** [comment]
Haha. This is just my experiment. As a widely adopted blocklist, false positive is a major concern. I understand that. Thanks for your long-time efforts. I will use the list myself and may recommend it to friends though. ^_^

**Comment by sr093906** [comment]
Several other 'suspects' are act(ivity), engage (ment), CPA (cost per action), mta (multi touch attribution), attr(ibution)... Look at the genius in ad industry. 🤣

**Comment by sr093906** [comment]
Closed.

**Comment by jawz101** [comment]
Hey we're glad they are obvious or don't tie them to redirected ports from their primary domain.  Like if ads.google.com was instead done by routing traffic from Google.com port 35553 to an internally named server, a host file wouldn't work because you'd block their main page.

I also don't like those as companies that give each customer a subdomain with a customer identifier.  My OCD doesn't want every deltadna or DoubleClick domain because it's just a bunch of junk to look at.

I do like some names.  You can tell when a server admin is in charge of naming things instead of a developer.  Like they'll name a corporate proxy Cerberus (mythological 3 headed dog guarding the gates of hell.) 
Like Netflix has a tracking domain called ichnaea.netflix.com.  I looked it up and Ichnaea was another mythological character called The Tracker.  I dig stuff like that.

**Pull request closed without merging**
