### PR TITLE
Add fls-eu.amazon.de and fls-eu.amazon.nl

### PR DESCRIPTION
**Pull request by pietvanzoen**
Hallo! Couple more amazon domains. :)

### CODE REVIEW

**Comment by jawz101** [comment]
I got crap for blocking it https://github.com/StevenBlack/hosts/issues/1468

**Comment by pietvanzoen** [comment]
As far as I can see the Amazon app and website work fine with these blocked. 

I’m actually migrating from NextDNS to Pi-hole and these are domains NextDNS has in their Ads/Trackers blocklist. 

Figured it wouldn’t be a big change since there’s already `fls-eu.amazon.com` in there. 🤷‍♂️

**Comment by jawz101** [comment]
Well I just readded them and some I had removed earlier so we'll close this

**Comment by pietvanzoen** [comment]
Cool. Thanks!

**Comment by spirillen** [comment]
Thanks for sharing @pietvanzoen

**Pull request closed without merging**
