### PR TITLE
update hosts

### PR DESCRIPTION
**Pull request by jawz101**
collected mobile ad, analytics, tracking networks based on traffic collected from pfSense logs, Adaway logs, and NetGuard logs.  Additionally, not found on StevenBlack, mvps, hphosts, yoyo, Dan Pollock, and several other blocklists (no one targets mobile ads yet :/)

### CODE REVIEW

**Comment by dschuermann** [comment]
Great work!

**Comment by jawz101** [comment]
Wow!  Thanks.  Some might be debatable.  Like crittercism and crashylitics do advertise as bug reporting _and_ analytics but devs _could_ use standard reporting mechanisms.  Also, I don't know if blocking some app-related collectors mean a cache of logs will accumulate on your phone.  I don't really think about it and clean caches.  I've never seen adverse effects with any of these blocks.

**Comment by dschuermann** [comment]
I think blocking these makes sense, I mean google analytics is also blocked by default.

**Comment by dschuermann** [comment]
@jawz101 Unfortunately, I needed to revert the pull request, there are some CDN hostnames in it that makes unusable. You can make a new pull request without those. See https://github.com/AdAway/adaway.github.io/commit/18bc338ae52069536c6b4ca1574f73c1ab1eb973#commitcomment-20680840

**Pull request merged**
