### PR TITLE
hosts.txt - Removing dead and inactive domains

### PR DESCRIPTION
**Pull request by smed79**
Removed domains:
```
click.buzzcity.net
ads.admoda.com
ad.madvertise.de
apps.buzzcity.net
show.buzzcity.net
admicro2.vcmedia.vn
medrx.sensis.com.au
adserver.ubiyoo.com
ads.n-ws.org
ads.smartdevicemedia.com
ads.adiquity.com
cdn.us.goldspotmedia.com
ads2.mediaarmor.com
ads.ookla.com
sf.vserv.mobi
atti.velti.com
uk-ad2.adinfuse.com
go.adinfuse.com
ad1.adinfuse.com
ad2.adinfuse.com
sky.adinfuse.com
orange-fr.adinfuse.com
sky-connect.adinfuse.com
uk-go.adinfuse.com
orangeuk-mc.adinfuse.com
intouch.adinfuse.com
funnel0.adinfuse.com
neptune.appads.com
neptune1.appads.com
neptune2.appads.com
neptune3.appads.com
saturn.appads.com
saturn1.appads.com
saturn2.appads.com
saturn3.appads.com
jupiter.appads.com
jupiter1.appads.com
jupiter2.appads.com
jupiter3.appads.com
req.appads.com
req1.appads.com
req2.appads.com
req3.appads.com
c29new.smaato.net
c01.smaato.net
c02.smaato.net
c03.smaato.net
c04.smaato.net
c05.smaato.net
c06.smaato.net
c07.smaato.net
c08.smaato.net
c09.smaato.net
c10.smaato.net
c11.smaato.net
c12.smaato.net
c13.smaato.net
c14.smaato.net
c15.smaato.net
c16.smaato.net
c17.smaato.net
c18.smaato.net
c19.smaato.net
c20.smaato.net
c21.smaato.net
c22.smaato.net
c23.smaato.net
c24.smaato.net
c25.smaato.net
c26.smaato.net
c27.smaato.net
c28.smaato.net
c29.smaato.net
c30.smaato.net
c31.smaato.net
c32.smaato.net
c33.smaato.net
c34.smaato.net
c35.smaato.net
c36.smaato.net
c37.smaato.net
c38.smaato.net
c39.smaato.net
c40.smaato.net
c41.smaato.net
c42.smaato.net
c43.smaato.net
c44.smaato.net
c45.smaato.net
c46.smaato.net
c47.smaato.net
c48.smaato.net
c49.smaato.net
c50.smaato.net
c51.smaato.net
c52.smaato.net
c53.smaato.net
c54.smaato.net
c55.smaato.net
c56.smaato.net
c57.smaato.net
c58.smaato.net
c59.smaato.net
f03.smaato.net
f04.smaato.net
f05.smaato.net
f06.smaato.net
f07.smaato.net
f08.smaato.net
f09.smaato.net
f10.smaato.net
f11.smaato.net
f12.smaato.net
f13.smaato.net
f14.smaato.net
f15.smaato.net
f16.smaato.net
f17.smaato.net
f18.smaato.net
f19.smaato.net
f20.smaato.net
f21.smaato.net
f22.smaato.net
f23.smaato.net
f24.smaato.net
f25.smaato.net
f26.smaato.net
f27.smaato.net
f28.smaato.net
f29.smaato.net
f30.smaato.net
f31.smaato.net
f32.smaato.net
f33.smaato.net
f34.smaato.net
f35.smaato.net
f36.smaato.net
f37.smaato.net
f38.smaato.net
f39.smaato.net
f40.smaato.net
f41.smaato.net
f42.smaato.net
f43.smaato.net
f44.smaato.net
f45.smaato.net
f46.smaato.net
f47.smaato.net
f48.smaato.net
f49.smaato.net
f50.smaato.net
f51.smaato.net
f52.smaato.net
f53.smaato.net
f54.smaato.net
f55.smaato.net
f56.smaato.net
f57.smaato.net
f58.smaato.net
f59.smaato.net
f60.smaato.net
tcy.smartadserver.com
a.admob.com
analytics.admob.com
p.admob.com
met.adwhirl.com
mob.adwhirl.com
pagead.googlesyndication.com
pagead1.googlesyndication.com
cdn.ajillionmax.com
t.medialytics.com
```
 Credit to @funilrys / using [funceble](https://github.com/funilrys/funceble).

### CODE REVIEW

**Comment by Vankog** [comment]
How often and over what period did you check these?
I'd really like to see only those domains removed, for which we can be reasonably sure they are dead. Some may be only down temporarily.

**Comment by funilrys** [comment]
@Vankog it can be check when you want but actually as it's listed to [dead-hosts](https://github.com/funilrys/dead-hosts/) once I'm done with review of the structure and scripts along with it, a full checkup is launched every 5 days. 

As it can be different for every list I'm working on a script/system to check after x day(s) :)

**Comment by funilrys** [comment]
@Vankog You can also take a look at https://github.com/mitchellkrogza/Badd-Boyz-Hosts to see how did we implement the run of [funceble](https://github.com/funilrys/funceble/tree/dev) with Travis CI.

**Comment by funilrys** [comment]
Hello there ! 
Can I know who is the maintainer of this repository? 

I created https://github.com/dead-hosts/adaway.github.io_git_AdAway and I want to add the maintainers as admin of that repository as it's a test of your repository... 

Cheers,
Nissar

**Comment by funilrys** [comment]
@Vankog Just an update with https://github.com/dead-hosts/adaway.github.io_git_AdAway we retest all inactive domain if current test date > 1 day + last test date

**Comment by Vankog** [comment]
We should probably clean out the hosts.txt to a bare minimum anyway.
We don't have the resources and time tomaintain this list properly. Fortunately there are lot of open source alternatives out there.

**Comment by smed79** [comment]
> We don't have the resources and time to maintain this list properly.

I volunteer to maintain AdAway [hosts](https://github.com/AdAway/adaway.github.io/blob/master/hosts.txt) file.

**Comment by PerfectSlayer** [comment]
> We don't have the resources and time to maintain this list properly.
But I'm open to any new hosts maintainer 😉 

@smed79 What is you policy about the hosts update? Only trim old domains? Add news ones?
@funilrys You also seem very active on this topic. Are you interested too? Maybe more about the automation side?

**Comment by smed79** [comment]
> What is you policy about the hosts update?

- block domains serving adverts
- block domains used for tracking purpose
- removing old/dead inactive domains
- remove or disable problematic blocked domains
- avoid redundancy with [default hosts sources](https://github.com/AdAway/AdAway/wiki/HostsSources#adaways-default-hosts-sources)
- avoid blocking [useful domains](https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/master/domains.list)

or better, _you set up a policy guide that i/we have to follow for updating the hosts file_.

**Comment by jawz101** [comment]
I'd love it if the list I maintain would have more eyes on it.  I scrub it with PyFunceble every so often but it would also be nice to have more scrutiny.  I primarily try to focus on mobile ad & tracking networks but there is a little spillover into browser-based domains I'm sure, but I try to keep it minimal.  I've also pulled in the Adguard mobile ads list, a few iOS ad networks, some ad networks not necessarily for my part of the world, & those detected by the Exodus privacy project but, with the Exodus Privacy Project, I mainly ended up adding more trackers to their signature list based on what I've gathered from actual app use.  The list avoids causing breakage such as not globally blocking graph.facebook.com but it will block all video incentive ads (e.g. get more energy by watching ads.)  Does save a ton of bandwidth but if you're into those types of games you might be constantly toggling the list off.

https://github.com/jawz101/MobileAdTrackers

**Comment by jawz101** [comment]
I'd love it if the list I maintain would have more eyes on it or have it taken over as the Adaway list. My list gets funnelled into a few aggregated lists but Adaway is sourced by even more. I scrub it with PyFunceble every so often but it would also be nice to have more scrutiny.

I primarily try to focus on mobile ad & tracking networks.  There is a little spillover into browser-based domains I'm sure, but I try to keep it minimal.

I've also pulled in the Adguard mobile ads list, a few iOS ad networks, some international ad networks, & some detected by the Exodus privacy project (but with the Exodus Privacy Project, I mainly ended up contributing trackers signatures based on _my_ observations :/)

https://github.com/jawz101/MobileAdTrackers

**Comment by PerfectSlayer** [comment]
Hi all,

@smed79 About the policy, I am not sure I am the most qualified to do this. I am mainly a developer and I don't really have a great background knowledge about ad and tracking networks.
I would say the better it blocks, the better it is. But it could cause some issues with certain apps. I wish I have a better help support to get user white listing domain than GitHub issue (may add some builtin rules?).

@jawz101 If you would like to merge your list into the AdAway one and have more visibility, you are free to go!

For the first times, please make PR that I will merge then I will grant you the write access if everything feels right and promote you as host maintainer 😉  (It is the repo that store and publish the home website, I want to be sure nothing bad will be posted on the home page 😅). Is it okay for both of you? Thanks!

**Comment by Vankog** [comment]
Just for your information. During the years we had dozens of opened issues and PRs from the whole community proposing hosts changes and improvements. 
If you want to take care of the AdAway host file (or even several host files? *nudge *nudge ;-)), I'd really love to see these threads and PRs looked through and taken into account as well. 
It would be a shame to ignore these contributions. And it wouldn't be fair as well. 
Thanks! :-)

**Comment by jawz101** [comment]
Thank you for the opportunity.  I would be ok with having some contributor rights as long as there is at least an additional person with the same privelege and interest.  @smed79 and @vankog seem to be likeminded and I would appreciate the idea of a few stewards.  Personally, I would replace the entire list with mine and remove anything that gets reported.  The current list is simply not effective anymore.

**Comment by smed79** [comment]
Closing..., will be treated in https://github.com/AdAway/adaway.github.io/pull/13

**Pull request closed without merging**
